JAIL_NAME="apimapper"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(GET|POST|HEAD) .*(/swagger-ui|/openapi\.json|/swagger\.json|/v[1-3]/api-docs|/api-docs|/graphiql|/graphql/schema).*\" (403|404) "
JAIL_MAXRETRY=2
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1595"
JAIL_MITRE_NAME="Active Scanning"