JAIL_NAME="badbots"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(Nuclei|sqlmap|Nikto|ZmEu|masscan|zgrab|Nmap|DirBuster|gobuster|httpx)\""
JAIL_MAXRETRY=1
JAIL_BANTIME="172800s" # 48 Hours
JAIL_MITRE_ID="T1595"
JAIL_MITRE_NAME="Active Scanning"