JAIL_NAME="drupal"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"POST .*(/user/login|\?q=user/login).*\" 200"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"