JAIL_NAME="gitlab"
JAIL_LOGPATHS="/var/log/gitlab/gitlab-rails/application.log /var/log/gitlab/gitlab-rails/auth.log"
JAIL_REGEX="(Failed Login|Authentication failed|ActionController::InvalidAuthenticityToken).*IP:? ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=5
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"