JAIL_NAME="grafana"
JAIL_LOGPATHS="/var/log/grafana/grafana.log"
JAIL_REGEX="(msg=\"Invalid username or password\"|status=401).*remote_addr=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"