JAIL_NAME="jenkins"
JAIL_LOGPATHS="/var/log/jenkins/jenkins.log"
JAIL_REGEX="(unsuccessfulAuthentication|Login attempt failed|Invalid password/token).* from ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=5
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"