JAIL_NAME="jndi-ssti"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*(\$\{jndi:|\%24\%7Bjndi:|class\.module\.classLoader|\%24\%7Bspring\.macro)"
JAIL_MAXRETRY=1
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1190"
JAIL_MITRE_NAME="Exploit Public-Facing Application"