JAIL_NAME="lfi-advanced"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(GET|POST|HEAD|PUT) .*(php://|file://|/etc/passwd|/etc/shadow|\%00)"
JAIL_MAXRETRY=1
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1190"
JAIL_MITRE_NAME="Exploit Public-Facing Application"