JAIL_NAME="mariadb"
JAIL_LOGPATHS="/var/log/mysql/error.log /var/log/mariadb/mariadb.log"
JAIL_REGEX="[Aa]ccess denied for user .*@.'([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"