JAIL_NAME="mongodb"
JAIL_LOGPATHS="/var/log/mongodb/mongod.log"
JAIL_REGEX="(Authentication failed|SASL authentication .* failed|unauthorized).* ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"