JAIL_NAME="privesc"
JAIL_LOGPATHS="/var/log/auth-syswarden.log /var/log/auth.log /var/log/secure"
JAIL_REGEX="(pam_unix\((su|sudo):auth\): authentication failure|FAILED su).*rhost=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1068"
JAIL_MITRE_NAME="Exploitation for Privilege Escalation"