JAIL_NAME="proxmox"
JAIL_LOGPATHS="/var/log/daemon.log /var/log/syslog"
JAIL_REGEX="pvedaemon.*authentication failure; rhost=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"