JAIL_NAME="recidive"
JAIL_LOGPATHS="/var/log/syswarden-l7.log"
JAIL_REGEX="\[SysWarden-L7\] Ban ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+) \| Jail"
JAIL_MAXRETRY=3
JAIL_BANTIME="604800s" # 1 Week for Repeat Offenders
JAIL_MITRE_ID="T1133"
JAIL_MITRE_NAME="External Remote Services / Repeat Offender"