JAIL_NAME="secretshunter"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(GET|POST|HEAD|PUT) .*(/\.env|/\.git|/\.aws|/\.ssh|/id_rsa|/id_ed25519|/[^ ]*\.(sql|bak|swp|db|sqlite3?|zip|gz|yml|yaml)).*\" [0-9]{3} "
JAIL_MAXRETRY=1
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1552"
JAIL_MITRE_NAME="Unsecured Credentials / Cloud Discovery"