JAIL_NAME="sendmail-auth"
JAIL_LOGPATHS="/var/log/mail.log /var/log/maillog"
JAIL_REGEX="sm-mta.*\[([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\].*did not issue MAIL/EXPN/VRFY/ETRN"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"