JAIL_NAME="silent-scanner"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(GET|POST|HEAD|PUT|DELETE|OPTIONS|PROPFIND) .*\" (400|401|403|404|405|444) "
JAIL_MAXRETRY=20
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1595"
JAIL_MITRE_NAME="Active Scanning"