JAIL_NAME="squid"
JAIL_LOGPATHS="/var/log/squid/access.log"
JAIL_REGEX="^[ \t]*([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+) .*(TCP_DENIED|ERR_ACCESS_DENIED)"
JAIL_MAXRETRY=5
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1090"
JAIL_MITRE_NAME="Connection Proxy"