JAIL_NAME="sshd"
JAIL_LOGPATHS="/var/log/auth.log /var/log/secure"
JAIL_REGEX="(Failed password for .*|Invalid user .*) from ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="14400s" # 4 Hours
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"