JAIL_NAME="ssrf"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"(GET|POST|HEAD|PUT) .*(169\.254\.169\.254|latest/meta-data|metadata\.google\.internal)"
JAIL_MAXRETRY=1
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1552"
JAIL_MITRE_NAME="Unsecured Credentials / Cloud Discovery"