JAIL_NAME="telnet"
JAIL_LOGPATHS="/var/log/auth.log /var/log/secure /var/log/auth-syswarden.log"
JAIL_REGEX="(in\.telnetd|telnetd|login).* connect from .*([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)|login.*FAILED LOGIN.* ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="172800s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Telnet IoT Attack"