JAIL_NAME="vaultwarden"
JAIL_LOGPATHS="/var/log/vaultwarden/vaultwarden.log /vw-data/vaultwarden.log"
JAIL_REGEX="\[vaultwarden::api::identity\]\[(WARN|ERROR)\].*(Invalid password|Client IP).* ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"