JAIL_NAME="wordpress"
JAIL_LOGPATHS="/var/log/nginx/access.log /var/log/apache2/access.log /var/log/httpd/access_log"
JAIL_REGEX="^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)[ \t]+.*\"POST .*(wp-login\.php|xmlrpc\.php)"
JAIL_MAXRETRY=4
JAIL_BANTIME="86400s" # 24 Hours
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"