JAIL_NAME="zabbix"
JAIL_LOGPATHS="/var/log/zabbix/zabbix_server.log"
JAIL_REGEX="failed login of user .* from ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
JAIL_MAXRETRY=3
JAIL_BANTIME="86400s"
JAIL_MITRE_ID="T1110"
JAIL_MITRE_NAME="Brute Force / Password Guessing"