name: 🐞 (Français) Rapport de Bug (SysWarden)
description: Signaler une erreur, un crash ou un comportement inattendu du script.
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler un problème ! 
        Pour nous aider à corriger SysWarden rapidement, veuillez remplir ce formulaire avec précision.
        
        ⚠️ **Important :** N'oubliez pas de masquer votre IP publique et votre clé API AbuseIPDB dans les logs avant de poster.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Vérifications Préalables
      description: Avez-vous vérifié les points suivants ?
      options:
        - label: J'utilise la dernière version du script (v1.0+).
          required: true
        - label: J'ai vérifié que le problème n'a pas déjà été signalé dans les "Issues".
          required: true
        - label: Je lance bien le script en tant que **root** (ou sudo).
          required: true

  - type: dropdown
    id: os_distro
    attributes:
      label: Distribution Linux
      description: Sur quel système d'exploitation le problème survient-il ?
      options:
        - Debian 11 / 12
        - Ubuntu 20.04 / 22.04 / 24.04
        - AlmaLinux 8 / 9
        - Rocky Linux 8 / 9
        - RHEL 8 / 9
        - CentOS Stream
        - Autre (Préciser ci-dessous)
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: Version du Noyau (Kernel)
      description: Résultat de la commande `uname -r`
      placeholder: ex: 5.10.0-28-amd64
    validations:
      required: false

  - type: dropdown
    id: firewall_backend
    attributes:
      label: Backend Pare-feu détecté
      description: Quel pare-feu le script a-t-il tenté de configurer ? (Visible dans les logs)
      options:
        - Nftables (Debian/Ubuntu moderne)
        - Firewalld (RHEL/Alma/Rocky)
        - Iptables / IPSet (Legacy)
        - Je ne sais pas
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: Description du problème
      description: Que se passe-t-il ? Quel est le comportement attendu vs le comportement réel ?
      placeholder: "J'ai lancé l'installation, tout s'est bien passé, mais Fail2ban ne semble pas démarrer..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs d'installation & Erreurs
      description: |
        Copiez ici les dernières lignes du fichier `/var/log/syswarden-install.log` ou la sortie de votre terminal.
        Utilisez des blocs de code (```) pour la lisibilité.
      render: shell
      placeholder: |
        Exemple :
        [ERROR] Failed to download blocklist.
        [INFO] Reverting changes...
    validations:
      required: true

  - type: textarea
    id: service_status
    attributes:
      label: État des Services (Optionnel)
      description: Si le problème concerne Fail2ban ou le Reporter, collez ici le résultat de `systemctl status fail2ban` ou `syswarden-reporter`.
      render: shell

  - type: dropdown
    id: install_mode
    attributes:
      label: Mode d'Installation
      description: Quelle option de liste avez-vous choisie ?
      options:
        - 1) Standard List (~85k IPs)
        - 2) Critical List (~100k IPs)
        - 3) Custom List
    validations:
      required: true

  - type: input
    id: ssh_port
    attributes:
      label: Port SSH Configuré
      description: Avez-vous un port SSH par défaut (22) ou personnalisé ?
      placeholder: ex: 2222
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Contexte supplémentaire
      description: Avez-vous d'autres logiciels de sécurité installés ? (CrowdSec, UFW, autre firewall...)