name: Plumber Compliance
on:
  push:
    branches: [main]

# OSSF Scorecard: Enforce strict read-all at the top-level
permissions: read-all

jobs:
  plumber:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write   # required to upload SARIF to Code Scanning
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: getplumber/plumber@f128c7478695192b037a921f0b71399dcff2f3c8 # v0.3.70
        with:
          threshold: 80
