name: Plumber Compliance
on:
  push:
    branches: [main]
    tags: ['v*']

# OSSF Scorecard: Enforce strict read-all at the top-level
permissions:
  contents: read

jobs:
  plumber:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write          # required to securely push Plumber Score via OIDC
      security-events: write   # required to upload SARIF to Code Scanning
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: getplumber/plumber@fdd2a2d0555bb3b33cbb2efff3b955dea5a6bbf0 # v0.4.3
        with:
          score-push: true
          threshold: 80
