name: SysWarden Security Audit

# --- GLOBAL ENVIRONMENT VARIABLES ---
# Forces GitHub Actions to use Node.js 24 for all JavaScript-based actions,
# bypassing the upcoming Node.js 20 deprecation warnings.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**.sh'
      - '**.py'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - '**.sh'
      - '**.py'

jobs:
  # ==========================================
  # JOB 1: CODE HYGIENE (ShellCheck & shfmt)
  # ==========================================
  hygiene:
    name: Code Hygiene
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck on Bash scripts
        # Scan all .sh scripts with a minimum severity of 'warning'
        run: shellcheck --severity=warning *.sh

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v3
        
      - name: Check Bash formatting (shfmt)
        # -d: diff (do not modify files, fail if improperly formatted)
        # -i 4: indent with 4 spaces
        # -ci: correctly indent switch cases
        run: shfmt -d -i 4 -ci *.sh

  # ==========================================
  # JOB 2: SECRET SCANNING (Gitleaks)
  # ==========================================
  anti-leaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by Gitleaks to scan the entire commit history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================
  # JOB 3 : SAST & VULNERABILITIES (Trivy)
  # ==========================================
  sast:
    name: SAST & Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- OS Dependency Vulnerability Analysis (Trivy) ---
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1' # Block the CI if a critical vulnerability is found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'